server {
  listen 80;
  root /usr/share/nginx/html;
  types { application/wasm wasm; application/manifest+json webmanifest; }
  include /etc/nginx/mime.types;
  gzip on;
  gzip_types application/json application/javascript text/css application/wasm;
  location /assets/ { add_header Cache-Control "public, max-age=31536000, immutable"; }
  location = /sw.js { add_header Cache-Control "no-cache"; }
  location / { try_files $uri $uri/ /index.html; }
}
